# Generated by Django 5.2.6 on 2025-12-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a portrait photo for this team member.', null=True, upload_to='team_photos/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo_path',
            field=models.CharField(blank=True, help_text="Static path relative to the 'core' static folder, e.g. 'core/images/team/nursaya.jpg' (deprecated, use photo field instead)", max_length=255),
        ),
    ]
